before_script:
  - export RBNICS_SRCDIR=$PWD
  - export RBNICS_TEST_DATA="/data/RBniCS-test-data"
  - export PYTHONPATH=$RBNICS_SRCDIR:$PYTHONPATH
  - export DOLFIN_NOPLOT=1
  - cd $RBNICS_TEST_DATA && git pull origin master && cd $OLDPWD
stages:
  - test
run_tutorials:
  script: 
    - bash $RBNICS_TEST_DATA/bin/run_tutorials.sh
  stage: test
  artifacts:
    paths:
      - tutorials/*/*.out
      - tutorials/*/*.out_diff
      - tutorials/*/*.err
